import Head from "next/head";
import { LazyMap } from "./components/Map/index";
import { HomeButton, DrawerButton, SettingsButton } from "./components/Buttons/Button";

const Home = () => {
  return (
    <>
      <Head>
        <title>Bike Tour Report</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeButton />
        <DrawerButton />
        <SettingsButton />
        <LazyMap />
      </main>
    </>
  );
};

export default Home;